### ISSUE TITLE
TransferLearning Cifar10

### ISSUE THREAD

**Issue by maryamag85** [yitu-opensource/T2T-ViT#42]
thanks for your nice work!
I have some issue following the repo and run the code for transfer learning.
I get the pretrain model for cifar10 from the link and locate it in the appropriate location and then when I run the following code from repo:
CUDA_VISIBLE_DEVICES=0,1 transfer_learning.py --lr 0.05 --b 64 --num-classes 10 --img-size 224 --transfer-learning True --transfer-model /path/to/pretrained/T2T-ViT-19

(model path adjusted)
I face some issue like the state dictionary does not have same name as it is used in the model. I do not understand why this can happen. Is there any mismatch between code and pretrained model architecture?

 del state_dict['head' + '.weight']
KeyError: 'head.weight'

**Comment by yuanli2333** [comment]
Hi, 
What is the pretained model you used for cifar10? I guess you used wrong pretrained models. 
If you want to transfer training our t2t-vit on cifar, you should use the t2t-vit pretrained on ImageNet, so you should use the model at [here](https://github.com/yitu-opensource/T2T-ViT/releases/download/main/cifar10_t2t-vit_19_98.4.pth).

**Comment by maryamag85** [comment]
I have tried and tested with all of the cifar pretrained model with the command below
python  transfer_learning.py --lr 0.05 --b 64 --num-classes 10 --img-size 224 --transfer-learning True --transfer_model .\checkpoints\cifar10_t2t-vit-19_98.8.pth

the error I see is this 
(base) D:\T2T-ViT-main>python  transfer_learning.py --lr 0.05 --b 64 --num-classes 10 --img-size 224 --transfer-learning True --transfer_model .\checkpoints\cifar10_t2t-vit-19_98.8.pth
==> Preparing data..
Files already downloaded and verified
Files already downloaded and verified
learning rate:0.05, weight decay: 0.0005
==> Building model..
adopt performer encoder for tokens-to-token
transfer learning, load t2t-vit pretrained model
> d:\t2t-vit-main\transfer_learning.py(135)<module>()
-> load_for_transfer_learning(net, args.transfer_model, use_ema=True, strict=True, num_classes=args.num_classes)
(Pdb) c
No checkpoint found at '.\checkpoints\cifar10_t2t-vit-19_98.8.pth'
Traceback (most recent call last):
  File "transfer_learning.py", line 135, in <module>
    load_for_transfer_learning(net, args.transfer_model, use_ema=True, strict=True, num_classes=args.num_classes)
  File "D:\T2T-ViT-main\utils.py", line 58, in load_for_transfer_learning
    state_dict = load_state_dict(checkpoint_path, use_ema, num_classes)
  File "D:\T2T-ViT-main\utils.py", line 54, in load_state_dict
    raise FileNotFoundError()
FileNotFoundError




I also noticed there is a typo in the code, transfer-learning is set in the args but when it is called it is written transfer_learning
_ is replaced with -

**Comment by maryamag85** [comment]
Thanks for the reply

I have tested with the model in the link and still no luck. I see the model starts with cifar name and I guess maybe that is already trained on cifar? however I tested with some other models which are provided on github and said they are trained on imagenet. I get errors related to dictionary mismatch like this 


(base) D:\T2T-ViT>python  transfer_learning.py --lr 0.05 --b 64 --num-classes 10 --img-size 224 --transfer-learning True --transfer_model .\checkpoints\cifar10_t2t-vit_19_98.4.pth
==> Preparing data..
Files already downloaded and verified
Files already downloaded and verified
learning rate:0.05, weight decay: 0.0005
==> Building model..
adopt performer encoder for tokens-to-token
transfer learning, load t2t-vit pretrained model
Traceback (most recent call last):
  File "transfer_learning.py", line 134, in <module>
    load_for_transfer_learning(net, args.transfer_model, use_ema=True, strict=False, num_classes=args.num_classes)
  File "D:\T2T-ViT\utils.py", line 56, in load_for_transfer_learning
    state_dict = load_state_dict(checkpoint_path, use_ema, num_classes)
  File "D:\T2T-ViT\utils.py", line 46, in load_state_dict
    del state_dict['head' + '.weight']
KeyError: 'head.weight'

I have played along and changed some of the code but it seems there are more than one mismatches between code and model.
There is also typo in the transfer_learning code like : transfer_model is written transfer-model in the arg list. _ is replaced with _

**Comment by maryamag85** [comment]
Thanks for clarification. I am still a bit unclear about naming convention you have in the repo. When the model is already started with cifar, I assumed it is trained on cifar or fine tuned on cifar. 
When I want to transfer a pretrained model like imagenet, regardless of the downstream task, it has a unique name. 
Also in the main.py and transfer_learning.py there are many mismatch variables specially in args and the main body, args like transfer_model is defined with _ and then used in the body like transfer-learning with -. which makes the code inconsistent. (there are several examples like this in the code)
in the main.py, that you mentioned can be used for validation, it always initialize the train loader etc, while in validation mode, there should not be a need to go over all training steps. In my opinion. I hope I am clear bout my points.
Finally, after fixing those syntax, I was able to fine-tune the pretrained model on image on my own dataset, but in validation time, the result is not good. Would you mind checking the code thoroughly and giving me some hint, where the issue can be? 
I use 81.5_T2T_ViT_14.pth.tar model as a pretrained model, then I setup dataloader to load my data and fine tune the model on my own data. Then with the main.py sample code I try to get the final check point of the transfer learning and test on my own dataset. with gives me around 50% accuracy. I strictly follow the sample code you provided with minor fixes I mentioned.

Thank you for your time and effort. I hope this wonderful repo gets mature sooner and people can leverage this model easier.

**Comment by yuanli2333** [comment]
HI,

Thanks for your suggestions!
I would make the name of madels be more consisitent recently.

**Comment by hqcheng-cqu** [comment]
你好，请问为什么--model t2t_vit_19 --transfer-model /xxx/cifar10_t2t-vit_19_98.4.pth 
也发生同样错误？
del state_dict['head' + '.weight']
KeyError: 'head.weight'
